apiVersion: v1
kind: Service 
metadata:
  name: {{ .Values.fullname }}
  labels:
    app: {{ .Values.fullname }}
spec:
  type: NodePort
  ports:
  - port: 80 # this is port on which service is running
    targetPort: {{ .Values.targetPort }} # port where container is running
  selector:
    app: {{ .Values.fullname }}